---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-ecs-writer
  namespace: default
rules:
- apiGroups:
  - ecs.services.k8s.aws
  resources:
  - capacityproviders
  - clusters
  - services
  - taskdefinitions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ecs.services.k8s.aws
  resources:
  - capacityproviders
  - clusters
  - services
  - taskdefinitions
  verbs:
  - get
  - patch
  - update
