// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package capacity_provider

import (
	"bytes"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
	"k8s.io/apimachinery/pkg/api/equality"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.AutoScalingGroupProvider, b.ko.Spec.AutoScalingGroupProvider) {
		delta.Add("Spec.AutoScalingGroupProvider", a.ko.Spec.AutoScalingGroupProvider, b.ko.Spec.AutoScalingGroupProvider)
	} else if a.ko.Spec.AutoScalingGroupProvider != nil && b.ko.Spec.AutoScalingGroupProvider != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.AutoScalingGroupProvider.AutoScalingGroupARN, b.ko.Spec.AutoScalingGroupProvider.AutoScalingGroupARN) {
			delta.Add("Spec.AutoScalingGroupProvider.AutoScalingGroupARN", a.ko.Spec.AutoScalingGroupProvider.AutoScalingGroupARN, b.ko.Spec.AutoScalingGroupProvider.AutoScalingGroupARN)
		} else if a.ko.Spec.AutoScalingGroupProvider.AutoScalingGroupARN != nil && b.ko.Spec.AutoScalingGroupProvider.AutoScalingGroupARN != nil {
			if *a.ko.Spec.AutoScalingGroupProvider.AutoScalingGroupARN != *b.ko.Spec.AutoScalingGroupProvider.AutoScalingGroupARN {
				delta.Add("Spec.AutoScalingGroupProvider.AutoScalingGroupARN", a.ko.Spec.AutoScalingGroupProvider.AutoScalingGroupARN, b.ko.Spec.AutoScalingGroupProvider.AutoScalingGroupARN)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.AutoScalingGroupProvider.ManagedDraining, b.ko.Spec.AutoScalingGroupProvider.ManagedDraining) {
			delta.Add("Spec.AutoScalingGroupProvider.ManagedDraining", a.ko.Spec.AutoScalingGroupProvider.ManagedDraining, b.ko.Spec.AutoScalingGroupProvider.ManagedDraining)
		} else if a.ko.Spec.AutoScalingGroupProvider.ManagedDraining != nil && b.ko.Spec.AutoScalingGroupProvider.ManagedDraining != nil {
			if *a.ko.Spec.AutoScalingGroupProvider.ManagedDraining != *b.ko.Spec.AutoScalingGroupProvider.ManagedDraining {
				delta.Add("Spec.AutoScalingGroupProvider.ManagedDraining", a.ko.Spec.AutoScalingGroupProvider.ManagedDraining, b.ko.Spec.AutoScalingGroupProvider.ManagedDraining)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.AutoScalingGroupProvider.ManagedScaling, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling) {
			delta.Add("Spec.AutoScalingGroupProvider.ManagedScaling", a.ko.Spec.AutoScalingGroupProvider.ManagedScaling, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling)
		} else if a.ko.Spec.AutoScalingGroupProvider.ManagedScaling != nil && b.ko.Spec.AutoScalingGroupProvider.ManagedScaling != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.InstanceWarmupPeriod, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.InstanceWarmupPeriod) {
				delta.Add("Spec.AutoScalingGroupProvider.ManagedScaling.InstanceWarmupPeriod", a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.InstanceWarmupPeriod, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.InstanceWarmupPeriod)
			} else if a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.InstanceWarmupPeriod != nil && b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.InstanceWarmupPeriod != nil {
				if *a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.InstanceWarmupPeriod != *b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.InstanceWarmupPeriod {
					delta.Add("Spec.AutoScalingGroupProvider.ManagedScaling.InstanceWarmupPeriod", a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.InstanceWarmupPeriod, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.InstanceWarmupPeriod)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MaximumScalingStepSize, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MaximumScalingStepSize) {
				delta.Add("Spec.AutoScalingGroupProvider.ManagedScaling.MaximumScalingStepSize", a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MaximumScalingStepSize, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MaximumScalingStepSize)
			} else if a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MaximumScalingStepSize != nil && b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MaximumScalingStepSize != nil {
				if *a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MaximumScalingStepSize != *b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MaximumScalingStepSize {
					delta.Add("Spec.AutoScalingGroupProvider.ManagedScaling.MaximumScalingStepSize", a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MaximumScalingStepSize, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MaximumScalingStepSize)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MinimumScalingStepSize, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MinimumScalingStepSize) {
				delta.Add("Spec.AutoScalingGroupProvider.ManagedScaling.MinimumScalingStepSize", a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MinimumScalingStepSize, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MinimumScalingStepSize)
			} else if a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MinimumScalingStepSize != nil && b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MinimumScalingStepSize != nil {
				if *a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MinimumScalingStepSize != *b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MinimumScalingStepSize {
					delta.Add("Spec.AutoScalingGroupProvider.ManagedScaling.MinimumScalingStepSize", a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MinimumScalingStepSize, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.MinimumScalingStepSize)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.Status, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.Status) {
				delta.Add("Spec.AutoScalingGroupProvider.ManagedScaling.Status", a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.Status, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.Status)
			} else if a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.Status != nil && b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.Status != nil {
				if *a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.Status != *b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.Status {
					delta.Add("Spec.AutoScalingGroupProvider.ManagedScaling.Status", a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.Status, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.Status)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.TargetCapacity, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.TargetCapacity) {
				delta.Add("Spec.AutoScalingGroupProvider.ManagedScaling.TargetCapacity", a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.TargetCapacity, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.TargetCapacity)
			} else if a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.TargetCapacity != nil && b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.TargetCapacity != nil {
				if *a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.TargetCapacity != *b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.TargetCapacity {
					delta.Add("Spec.AutoScalingGroupProvider.ManagedScaling.TargetCapacity", a.ko.Spec.AutoScalingGroupProvider.ManagedScaling.TargetCapacity, b.ko.Spec.AutoScalingGroupProvider.ManagedScaling.TargetCapacity)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.AutoScalingGroupProvider.ManagedTerminationProtection, b.ko.Spec.AutoScalingGroupProvider.ManagedTerminationProtection) {
			delta.Add("Spec.AutoScalingGroupProvider.ManagedTerminationProtection", a.ko.Spec.AutoScalingGroupProvider.ManagedTerminationProtection, b.ko.Spec.AutoScalingGroupProvider.ManagedTerminationProtection)
		} else if a.ko.Spec.AutoScalingGroupProvider.ManagedTerminationProtection != nil && b.ko.Spec.AutoScalingGroupProvider.ManagedTerminationProtection != nil {
			if *a.ko.Spec.AutoScalingGroupProvider.ManagedTerminationProtection != *b.ko.Spec.AutoScalingGroupProvider.ManagedTerminationProtection {
				delta.Add("Spec.AutoScalingGroupProvider.ManagedTerminationProtection", a.ko.Spec.AutoScalingGroupProvider.ManagedTerminationProtection, b.ko.Spec.AutoScalingGroupProvider.ManagedTerminationProtection)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Cluster, b.ko.Spec.Cluster) {
		delta.Add("Spec.Cluster", a.ko.Spec.Cluster, b.ko.Spec.Cluster)
	} else if a.ko.Spec.Cluster != nil && b.ko.Spec.Cluster != nil {
		if *a.ko.Spec.Cluster != *b.ko.Spec.Cluster {
			delta.Add("Spec.Cluster", a.ko.Spec.Cluster, b.ko.Spec.Cluster)
		}
	}
	if !equality.Semantic.Equalities.DeepEqual(a.ko.Spec.ClusterRef, b.ko.Spec.ClusterRef) {
		delta.Add("Spec.ClusterRef", a.ko.Spec.ClusterRef, b.ko.Spec.ClusterRef)
	}
	if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider, b.ko.Spec.ManagedInstancesProvider) {
		delta.Add("Spec.ManagedInstancesProvider", a.ko.Spec.ManagedInstancesProvider, b.ko.Spec.ManagedInstancesProvider)
	} else if a.ko.Spec.ManagedInstancesProvider != nil && b.ko.Spec.ManagedInstancesProvider != nil {
		if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.AutoRepairConfiguration, b.ko.Spec.ManagedInstancesProvider.AutoRepairConfiguration) {
			delta.Add("Spec.ManagedInstancesProvider.AutoRepairConfiguration", a.ko.Spec.ManagedInstancesProvider.AutoRepairConfiguration, b.ko.Spec.ManagedInstancesProvider.AutoRepairConfiguration)
		} else if a.ko.Spec.ManagedInstancesProvider.AutoRepairConfiguration != nil && b.ko.Spec.ManagedInstancesProvider.AutoRepairConfiguration != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.AutoRepairConfiguration.ActionsStatus, b.ko.Spec.ManagedInstancesProvider.AutoRepairConfiguration.ActionsStatus) {
				delta.Add("Spec.ManagedInstancesProvider.AutoRepairConfiguration.ActionsStatus", a.ko.Spec.ManagedInstancesProvider.AutoRepairConfiguration.ActionsStatus, b.ko.Spec.ManagedInstancesProvider.AutoRepairConfiguration.ActionsStatus)
			} else if a.ko.Spec.ManagedInstancesProvider.AutoRepairConfiguration.ActionsStatus != nil && b.ko.Spec.ManagedInstancesProvider.AutoRepairConfiguration.ActionsStatus != nil {
				if *a.ko.Spec.ManagedInstancesProvider.AutoRepairConfiguration.ActionsStatus != *b.ko.Spec.ManagedInstancesProvider.AutoRepairConfiguration.ActionsStatus {
					delta.Add("Spec.ManagedInstancesProvider.AutoRepairConfiguration.ActionsStatus", a.ko.Spec.ManagedInstancesProvider.AutoRepairConfiguration.ActionsStatus, b.ko.Spec.ManagedInstancesProvider.AutoRepairConfiguration.ActionsStatus)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InfrastructureOptimization, b.ko.Spec.ManagedInstancesProvider.InfrastructureOptimization) {
			delta.Add("Spec.ManagedInstancesProvider.InfrastructureOptimization", a.ko.Spec.ManagedInstancesProvider.InfrastructureOptimization, b.ko.Spec.ManagedInstancesProvider.InfrastructureOptimization)
		} else if a.ko.Spec.ManagedInstancesProvider.InfrastructureOptimization != nil && b.ko.Spec.ManagedInstancesProvider.InfrastructureOptimization != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InfrastructureOptimization.ScaleInAfter, b.ko.Spec.ManagedInstancesProvider.InfrastructureOptimization.ScaleInAfter) {
				delta.Add("Spec.ManagedInstancesProvider.InfrastructureOptimization.ScaleInAfter", a.ko.Spec.ManagedInstancesProvider.InfrastructureOptimization.ScaleInAfter, b.ko.Spec.ManagedInstancesProvider.InfrastructureOptimization.ScaleInAfter)
			} else if a.ko.Spec.ManagedInstancesProvider.InfrastructureOptimization.ScaleInAfter != nil && b.ko.Spec.ManagedInstancesProvider.InfrastructureOptimization.ScaleInAfter != nil {
				if *a.ko.Spec.ManagedInstancesProvider.InfrastructureOptimization.ScaleInAfter != *b.ko.Spec.ManagedInstancesProvider.InfrastructureOptimization.ScaleInAfter {
					delta.Add("Spec.ManagedInstancesProvider.InfrastructureOptimization.ScaleInAfter", a.ko.Spec.ManagedInstancesProvider.InfrastructureOptimization.ScaleInAfter, b.ko.Spec.ManagedInstancesProvider.InfrastructureOptimization.ScaleInAfter)
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InfrastructureRoleARN, b.ko.Spec.ManagedInstancesProvider.InfrastructureRoleARN) {
			delta.Add("Spec.ManagedInstancesProvider.InfrastructureRoleARN", a.ko.Spec.ManagedInstancesProvider.InfrastructureRoleARN, b.ko.Spec.ManagedInstancesProvider.InfrastructureRoleARN)
		} else if a.ko.Spec.ManagedInstancesProvider.InfrastructureRoleARN != nil && b.ko.Spec.ManagedInstancesProvider.InfrastructureRoleARN != nil {
			if *a.ko.Spec.ManagedInstancesProvider.InfrastructureRoleARN != *b.ko.Spec.ManagedInstancesProvider.InfrastructureRoleARN {
				delta.Add("Spec.ManagedInstancesProvider.InfrastructureRoleARN", a.ko.Spec.ManagedInstancesProvider.InfrastructureRoleARN, b.ko.Spec.ManagedInstancesProvider.InfrastructureRoleARN)
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate) {
			delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate)
		} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate != nil {
			if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityOptionType, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityOptionType) {
				delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityOptionType", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityOptionType, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityOptionType)
			} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityOptionType != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityOptionType != nil {
				if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityOptionType != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityOptionType {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityOptionType", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityOptionType, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityOptionType)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations) {
				delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations)
			} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationGroupARN, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationGroupARN) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationGroupARN", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationGroupARN, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationGroupARN)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationGroupARN != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationGroupARN != nil {
					if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationGroupARN != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationGroupARN {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationGroupARN", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationGroupARN, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationGroupARN)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationPreference, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationPreference) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationPreference", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationPreference, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationPreference)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationPreference != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationPreference != nil {
					if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationPreference != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationPreference {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationPreference", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationPreference, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.CapacityReservations.ReservationPreference)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.EC2InstanceProfileARN, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.EC2InstanceProfileARN) {
				delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.EC2InstanceProfileARN", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.EC2InstanceProfileARN, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.EC2InstanceProfileARN)
			} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.EC2InstanceProfileARN != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.EC2InstanceProfileARN != nil {
				if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.EC2InstanceProfileARN != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.EC2InstanceProfileARN {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.EC2InstanceProfileARN", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.EC2InstanceProfileARN, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.EC2InstanceProfileARN)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.FipsEnabled, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.FipsEnabled) {
				delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.FipsEnabled", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.FipsEnabled, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.FipsEnabled)
			} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.FipsEnabled != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.FipsEnabled != nil {
				if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.FipsEnabled != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.FipsEnabled {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.FipsEnabled", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.FipsEnabled, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.FipsEnabled)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceMetadataTagsPropagation, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceMetadataTagsPropagation) {
				delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceMetadataTagsPropagation", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceMetadataTagsPropagation, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceMetadataTagsPropagation)
			} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceMetadataTagsPropagation != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceMetadataTagsPropagation != nil {
				if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceMetadataTagsPropagation != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceMetadataTagsPropagation {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceMetadataTagsPropagation", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceMetadataTagsPropagation, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceMetadataTagsPropagation)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements) {
				delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements)
			} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Max) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Max)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Max != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Max != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Max != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Max {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Max)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Min) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Min)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Min != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Min != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Min != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Min {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorCount.Min)
						}
					}
				}
				if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorManufacturers) != len(b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorManufacturers) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorManufacturers", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorManufacturers, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorManufacturers)
				} else if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorManufacturers) > 0 {
					if !ackcompare.SliceStringPEqual(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorManufacturers, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorManufacturers) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorManufacturers", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorManufacturers, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorManufacturers)
					}
				}
				if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorNames) != len(b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorNames) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorNames", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorNames, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorNames)
				} else if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorNames) > 0 {
					if !ackcompare.SliceStringPEqual(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorNames, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorNames) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorNames", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorNames, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorNames)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Max) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Max)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Max != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Max != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Max != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Max {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Max)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Min) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Min)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Min != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Min != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Min != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Min {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTotalMemoryMiB.Min)
						}
					}
				}
				if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTypes) != len(b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTypes) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTypes", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTypes, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTypes)
				} else if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTypes) > 0 {
					if !ackcompare.SliceStringPEqual(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTypes, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTypes) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTypes", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTypes, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AcceleratorTypes)
					}
				}
				if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AllowedInstanceTypes) != len(b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AllowedInstanceTypes) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AllowedInstanceTypes", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AllowedInstanceTypes, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AllowedInstanceTypes)
				} else if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AllowedInstanceTypes) > 0 {
					if !ackcompare.SliceStringPEqual(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AllowedInstanceTypes, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AllowedInstanceTypes) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AllowedInstanceTypes", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AllowedInstanceTypes, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.AllowedInstanceTypes)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BareMetal, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BareMetal) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BareMetal", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BareMetal, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BareMetal)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BareMetal != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BareMetal != nil {
					if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BareMetal != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BareMetal {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BareMetal", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BareMetal, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BareMetal)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Max) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Max)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Max != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Max != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Max != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Max {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Max)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Min) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Min)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Min != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Min != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Min != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Min {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BaselineEBSBandwidthMbps.Min)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BurstablePerformance, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BurstablePerformance) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BurstablePerformance", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BurstablePerformance, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BurstablePerformance)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BurstablePerformance != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BurstablePerformance != nil {
					if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BurstablePerformance != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BurstablePerformance {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BurstablePerformance", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BurstablePerformance, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.BurstablePerformance)
					}
				}
				if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.CPUManufacturers) != len(b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.CPUManufacturers) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.CPUManufacturers", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.CPUManufacturers, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.CPUManufacturers)
				} else if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.CPUManufacturers) > 0 {
					if !ackcompare.SliceStringPEqual(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.CPUManufacturers, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.CPUManufacturers) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.CPUManufacturers", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.CPUManufacturers, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.CPUManufacturers)
					}
				}
				if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.ExcludedInstanceTypes) != len(b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.ExcludedInstanceTypes) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.ExcludedInstanceTypes", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.ExcludedInstanceTypes, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.ExcludedInstanceTypes)
				} else if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.ExcludedInstanceTypes) > 0 {
					if !ackcompare.SliceStringPEqual(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.ExcludedInstanceTypes, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.ExcludedInstanceTypes) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.ExcludedInstanceTypes", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.ExcludedInstanceTypes, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.ExcludedInstanceTypes)
					}
				}
				if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.InstanceGenerations) != len(b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.InstanceGenerations) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.InstanceGenerations", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.InstanceGenerations, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.InstanceGenerations)
				} else if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.InstanceGenerations) > 0 {
					if !ackcompare.SliceStringPEqual(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.InstanceGenerations, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.InstanceGenerations) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.InstanceGenerations", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.InstanceGenerations, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.InstanceGenerations)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorage, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorage) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorage", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorage, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorage)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorage != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorage != nil {
					if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorage != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorage {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorage", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorage, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorage)
					}
				}
				if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorageTypes) != len(b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorageTypes) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorageTypes", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorageTypes, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorageTypes)
				} else if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorageTypes) > 0 {
					if !ackcompare.SliceStringPEqual(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorageTypes, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorageTypes) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorageTypes", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorageTypes, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.LocalStorageTypes)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice != nil {
					if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MaxSpotPriceAsPercentageOfOptimalOnDemandPrice)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Max) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Max)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Max != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Max != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Max != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Max {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Max)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Min) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Min)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Min != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Min != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Min != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Min {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryGiBPerVCPU.Min)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Max) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Max)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Max != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Max != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Max != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Max {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Max)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Min) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Min)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Min != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Min != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Min != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Min {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.MemoryMiB.Min)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Max) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Max)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Max != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Max != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Max != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Max {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Max)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Min) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Min)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Min != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Min != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Min != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Min {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkBandwidthGbps.Min)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Max) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Max)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Max != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Max != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Max != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Max {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Max)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Min) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Min)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Min != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Min != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Min != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Min {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.NetworkInterfaceCount.Min)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice != nil {
					if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.OnDemandMaxPricePercentageOverLowestPrice)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.RequireHibernateSupport, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.RequireHibernateSupport) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.RequireHibernateSupport", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.RequireHibernateSupport, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.RequireHibernateSupport)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.RequireHibernateSupport != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.RequireHibernateSupport != nil {
					if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.RequireHibernateSupport != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.RequireHibernateSupport {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.RequireHibernateSupport", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.RequireHibernateSupport, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.RequireHibernateSupport)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice != nil {
					if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.SpotMaxPricePercentageOverLowestPrice)
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Max) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Max)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Max != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Max != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Max != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Max {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Max)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Min) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Min)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Min != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Min != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Min != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Min {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.TotalLocalStorageGB.Min)
						}
					}
				}
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount != nil {
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Max) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Max)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Max != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Max != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Max != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Max {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Max", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Max, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Max)
						}
					}
					if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Min) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Min)
					} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Min != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Min != nil {
						if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Min != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Min {
							delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Min", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Min, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.InstanceRequirements.VCPUCount.Min)
						}
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration) {
				delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration)
			} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration.UseLocalStorage, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration.UseLocalStorage) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration.UseLocalStorage", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration.UseLocalStorage, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration.UseLocalStorage)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration.UseLocalStorage != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration.UseLocalStorage != nil {
					if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration.UseLocalStorage != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration.UseLocalStorage {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration.UseLocalStorage", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration.UseLocalStorage, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.LocalStorageConfiguration.UseLocalStorage)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.Monitoring, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.Monitoring) {
				delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.Monitoring", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.Monitoring, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.Monitoring)
			} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.Monitoring != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.Monitoring != nil {
				if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.Monitoring != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.Monitoring {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.Monitoring", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.Monitoring, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.Monitoring)
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration) {
				delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration)
			} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration != nil {
				if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.SecurityGroups) != len(b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.SecurityGroups) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.SecurityGroups", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.SecurityGroups, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.SecurityGroups)
				} else if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.SecurityGroups) > 0 {
					if !ackcompare.SliceStringPEqual(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.SecurityGroups, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.SecurityGroups) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.SecurityGroups", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.SecurityGroups, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.SecurityGroups)
					}
				}
				if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.Subnets) != len(b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.Subnets) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.Subnets", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.Subnets, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.Subnets)
				} else if len(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.Subnets) > 0 {
					if !ackcompare.SliceStringPEqual(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.Subnets, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.Subnets) {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.Subnets", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.Subnets, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.NetworkConfiguration.Subnets)
					}
				}
			}
			if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration) {
				delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration)
			} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration != nil {
				if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration.StorageSizeGiB, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration.StorageSizeGiB) {
					delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration.StorageSizeGiB", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration.StorageSizeGiB, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration.StorageSizeGiB)
				} else if a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration.StorageSizeGiB != nil && b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration.StorageSizeGiB != nil {
					if *a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration.StorageSizeGiB != *b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration.StorageSizeGiB {
						delta.Add("Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration.StorageSizeGiB", a.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration.StorageSizeGiB, b.ko.Spec.ManagedInstancesProvider.InstanceLaunchTemplate.StorageConfiguration.StorageSizeGiB)
					}
				}
			}
		}
		if ackcompare.HasNilDifference(a.ko.Spec.ManagedInstancesProvider.PropagateTags, b.ko.Spec.ManagedInstancesProvider.PropagateTags) {
			delta.Add("Spec.ManagedInstancesProvider.PropagateTags", a.ko.Spec.ManagedInstancesProvider.PropagateTags, b.ko.Spec.ManagedInstancesProvider.PropagateTags)
		} else if a.ko.Spec.ManagedInstancesProvider.PropagateTags != nil && b.ko.Spec.ManagedInstancesProvider.PropagateTags != nil {
			if *a.ko.Spec.ManagedInstancesProvider.PropagateTags != *b.ko.Spec.ManagedInstancesProvider.PropagateTags {
				delta.Add("Spec.ManagedInstancesProvider.PropagateTags", a.ko.Spec.ManagedInstancesProvider.PropagateTags, b.ko.Spec.ManagedInstancesProvider.PropagateTags)
			}
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Name, b.ko.Spec.Name) {
		delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
	} else if a.ko.Spec.Name != nil && b.ko.Spec.Name != nil {
		if *a.ko.Spec.Name != *b.ko.Spec.Name {
			delta.Add("Spec.Name", a.ko.Spec.Name, b.ko.Spec.Name)
		}
	}
	desiredACKTags, _ := convertToOrderedACKTags(a.ko.Spec.Tags)
	latestACKTags, _ := convertToOrderedACKTags(b.ko.Spec.Tags)
	if !ackcompare.MapStringStringEqual(desiredACKTags, latestACKTags) {
		delta.Add("Spec.Tags", a.ko.Spec.Tags, b.ko.Spec.Tags)
	}

	return delta
}
